"""
Generate a report listing Riks and Samams that are missing metadata (Rishi, Devata, Chandas).
Reads from: data/output/JSV_Samam_Granular_Table.csv
Outputs to: data/output/JSV_Missing_Metadata_Report.md
"""
import csv
import os
import datetime

INPUT_CSV = r'data\output\JSV_Samam_Granular_Table.csv'
OUTPUT_MD = r'data\output\JSV_Missing_Metadata_Report.md'
OUTPUT_CSV = r'data\output\JSV_Missing_Metadata.csv'

def check_missing_metadata():
    print(f"Checking for missing metadata in {INPUT_CSV}...")
    
    if not os.path.exists(INPUT_CSV):
        print(f"Error: Input file {INPUT_CSV} not found.")
        return

    missing_entries = []
    
    with open(INPUT_CSV, 'r', encoding='utf-8-sig') as f:
        # Skip the first line usually containing metadata (Filename Version Timestamp)
        # But wait, the generate_granular_table.py writes a metadata line first: f.write(f"{filename} {JSV_VERSION} {GENERATED_AT}\n")
        # And then writer.writeheader()
        
        # So we need to handle that.
        first_line = f.readline()
        # If the file was just generated by our script, the first line is metadata, second is header.
        # But DictReader might consume the first line as header if we don't skip it, 
        # OR if we pass fieldnames it might work differently.
        # Let's peek. The script writes:
        # f.write(...) \n
        # writer.writeheader()
        
        # So yes, readline() skips the arbitrary metadata line.
        
        reader = csv.DictReader(f)
        
        for row in reader:
            missing_fields = []
            
            # Check Rik Metadata
            if not row.get('Rik_Rishi', '').strip(): missing_fields.append('Rik_Rishi')
            if not row.get('Rik_Devata', '').strip(): missing_fields.append('Rik_Devata')
            if not row.get('Rik_Chandas', '').strip(): missing_fields.append('Rik_Chandas')
            
            # Check Samam Metadata
            if not row.get('Samam_Rishi', '').strip(): missing_fields.append('Samam_Rishi')
            if not row.get('Samam_Devata', '').strip(): missing_fields.append('Samam_Devata')
            if not row.get('Samam_Chandas', '').strip(): missing_fields.append('Samam_Chandas')
            
            if missing_fields:
                entry = {
                    'Patha': row['Patha_Name'],
                    'Khanda': row['Khanda'],
                    'Rik_ID': row['Rik_ID'],
                    'Samam_Num': row['Samam_Num'], # Global_Samam_Num or local Samam_Num? Usually local is better for locating.
                    'Global_Samam_Num': row['Global_Samam_Num'],
                    'Missing': ', '.join(missing_fields)
                }
                missing_entries.append(entry)

    # Generate Reports
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # 1. Markdown Report
    with open(OUTPUT_MD, 'w', encoding='utf-8') as f:
        f.write(f"# JSV Missing Metadata Report\n\n")
        f.write(f"**Generated:** {timestamp}\n")
        f.write(f"**Total Issues Found:** {len(missing_entries)}\n\n")
        
        if missing_entries:
            f.write("| Patha | Khanda | Rik ID | Samam Num | Missing Fields |\n")
            f.write("|---|---|---|---|---|\n")
            for e in missing_entries:
                f.write(f"| {e['Patha']} | {e['Khanda']} | {e['Rik_ID']} | {e['Samam_Num']} | {e['Missing']} |\n")
        else:
            f.write("✅ **No missing metadata found!** All Riks and Samams have Rishi, Devata, and Chandas.\n")
            
    # 2. CSV Report (for easy filtering)
    if missing_entries:
        with open(OUTPUT_CSV, 'w', encoding='utf-8-sig', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=['Patha', 'Khanda', 'Rik_ID', 'Samam_Num', 'Global_Samam_Num', 'Missing'])
            writer.writeheader()
            writer.writerows(missing_entries)
        print(f"CSV report saved to {OUTPUT_CSV}")

    print(f"Markdown report saved to {OUTPUT_MD}")
    print(f"Total missing entries: {len(missing_entries)}")

if __name__ == "__main__":
    check_missing_metadata()
